### ISSUE TITLE
Fix Downtime page

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#97] opened 2016-01-25 19:47 UTC
Currently the downtime page doesn't pull any results.  We should discuss possible changes to the downtime workflow in Binder.

**Comment by minigeek** [comment] 2016-01-25 20:41
This may be due to config/lack of data. I believe that page only pulls data
from org's that have already taken some downtime rather than all org's (as
many org's will never take downtime or are incapable of it such as SCC).

**Comment by pkoenig10** [comment] 2016-01-25 20:50
In my testing, I couldn't get any taken downtime to show.  This may just be more of an investigative task.

**Comment by RONNCC** [comment] 2016-02-14 08:16
@pkoenig10  is this expected behavior? :) https://is67373-binder-app-ronncc.c9users.io/downtime

**Comment by RONNCC** [comment] 2016-02-14 10:22
Fix looks like: 
![image](https://cloud.githubusercontent.com/assets/1313566/13033176/e96ade6a-d2da-11e5-8d76-
0fec4bf2d2f5.png)

**Comment by arakla** [comment] 2016-02-14 18:29
This looks as expected in the dev version you are running. Although the
list of orgs should probably be building orgs only (in other words exclude
non-building orgs).

Non-building orgs can't take downtime because they don't have a booth.

**Comment by pkoenig10** [comment] 2016-02-14 19:22
+1 for updating the list of orgs.

Also, I think it would be good to always show all building orgs in the table, even those that haven't taken downtime yet.

**Comment by arakla** [comment] 2016-02-14 19:31
Also, side note for the sidebar, most actions, like creating downtime
entry, causes the entire page to refresh, something to look into is only
refreshing that section of the page using something, like AJAX. This would
greatly increase the efficiency of binder if certain things, like the nav
var weren't always reloaded.

I believe Prof H has AJAX examples in Arbeit.

**Comment by pkoenig10** [comment] 2016-02-14 19:38
To me this seems like a minor issue.  Lets punt this and not get it mixed up with the Downtime page issue.

**Comment by minigeek** [comment] 2016-02-14 19:50
This should also happen automatically in production thanks to rails.

**Comment by RONNCC** [comment] 2016-02-18 23:49
^ should be resolved by that

**Comment by RONNCC** [comment] 2016-02-18 23:50
![screenshot 2016-02-18 at 6 50 09 pm](https://cloud.githubusercontent.com/assets/1313566/13162091/7cddf3f6-d670-11e5-884d-a6c5fa1438e9.png)

**Closed** 2016-02-24 05:54 UTC
Labels: feedback:discussion, priority:critical, problem:bug, status:in-progress
