### ISSUE TITLE
Add weather widget to home dashboard

### ISSUE THREAD

**Issue by rjc210** [sc0v/binder-app#38] opened 2013-12-20 00:28 UTC
Cool feature that was discussed but outside of the scope of our project. Weather would be displayed within the app on the home dashboard so that the coordinator wouldn't have to watch weather separately to track storms.

**Comment by pkoenig10** [comment] 2016-01-24 19:37
Duplicate of #88

**Closed by pkoenig10** 2016-01-24 19:37 UTC
Labels: feature
